global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gradepro-gateway"
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: "gradepro-orchestrator"
    static_configs:
      - targets: ["orchestrator:8001"]

  - job_name: "gradepro-ml-inference"
    static_configs:
      - targets: ["ml_inference:8002"]

  - job_name: "gradepro-pdf-service"
    static_configs:
      - targets: ["pdf_service:8003"]
